name: Trigger auto deployment for webredditcloneapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/webredditcloneapp-AutoDeployTrigger-627fc00e-432c-4702-bec5-70d31767c6a8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.WEBREDDITCLONEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBREDDITCLONEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBREDDITCLONEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.WEBREDDITCLONEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBREDDITCLONEAPP_REGISTRY_PASSWORD }}
          containerAppName: webredditcloneapp
          resourceGroup: AZUREDEVRG
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


